# Generated by Django 4.2.7 on 2023-11-27 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_order_alter_category_options_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
